version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn install -DskipTests
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-depenencies-{{ checksum "pom.xml" }}

      - run: mvn test-compile

workflows:
  version: 2
  build-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - update-recipe